### ISSUE TITLE
issues with gatling 3.0

### ISSUE THREAD

**Issue by gjupalli** [mnogu/gatling-kafka#20]
we use this extension in one of the projects, thank you very much for providing this. however we noticed that if we change gatling version to 3.0 to build a new jar, it is throwing compilation errors. Looks like changes in gatling 3.0 protocol implementation, any help on how to fix these is appreciated.

**Comment by SujalAhrodia** [comment]
I have tried implementing the extension with gatling 3.0 as well and facing similar behaviour. 
I am facing the following errors after selecting the simulation file:

//Error:

21:28:01.794 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassNotFoundException: scala.Product$class
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: scala/Product$class
	at com.github.mnogu.gatling.kafka.protocol.KafkaProtocol.<init>(KafkaProtocol.scala:39)
	at com.github.mnogu.gatling.kafka.protocol.KafkaProtocol$.apply(KafkaProtocol.scala:10)
	at com.github.mnogu.gatling.kafka.protocol.KafkaProtocolBuilder$.apply(KafkaProtocolBuilder.scala:11)
	at com.github.mnogu.gatling.kafka.Predef$.kafka(Predef.scala:11)
//////

I believe another reason can be because of the incapability between gatling and the latest version of jdk. I am using gatling 3.0 with jdk 11.

**Comment by rroyoo** [comment]
I upgraded and tested the project to be compatible with gatling 3.0.

In PR#22 you have available the changes.

**Comment by mnogu** [comment]
I merged #22
