### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by SujalAhrodia** [mnogu/gatling-kafka#21]
On replicating the whole procedure on my macbook pro 2017, I am able to successfully create a jar as well as link the simulation file. However, while running the simulation I am facing the following error:

Simulation com.github.mnogu.gatling.kafka.test.KafkaSimulation started...
Uncaught error from thread [GatlingSystem-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[GatlingSystem]
**java.lang.NoClassDefFoundError: io/gatling/commons/util/ClockSingleton$**
	at com.github.mnogu.gatling.kafka.action.KafkaRequestAction$$anonfun$com$github$mnogu$gatling$kafka$action$KafkaRequestAction$$sendRequest$1.apply(KafkaRequestAction.scala:65)
	at com.github.mnogu.gatling.kafka.action.KafkaRequestAction$$anonfun$com$github$mnogu$gatling$kafka$action$KafkaRequestAction$$sendRequest$1.apply(KafkaRequestAction.scala:56)
	at io.gatling.commons.validation.Success.map(Validation.scala:32)
...
..
..

Can someone share any thoughts on the probable reason for this?

**Comment by WillNilges** [comment]
I'm getting similar errors with Gatling 3.4.1. ClockSingleton probably doesn't exist in that package anymore or something.
